services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: jules
      POSTGRES_PASSWORD: jules
      POSTGRES_DB: chronodebile
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
